### ISSUE TITLE
Great... but why use geany?

### ISSUE THREAD

**Issue by datatalking** [geany/www.geany.org#3]
I found Geany via a reference in the "python crash course" and I had never heard of it but I was curious... this code was updated almost two months ago and very little activity.

My question is this, what is the unique functionality of Geany that would make anyone use it over say sublime, atom, vim, emacs, Jupyter notebook, Pycharm or a dozen other widely used products or even Visual Studio.

I'm operating on ignorance here, having never had someone even say the word "Geany like Genie?" and wanted to know what is the point of Geany, what does it do that is special other than, text editor over a network which seems to be such a common function that it seems practically standard nowadays.

Perhaps Geany is a holdover from the Fortran days and is still being used by loyalists or?

**Comment by codebrainz** [comment]
> this code was updated almost two months ago and very little activity.

The source code repository is here: https://github.com/geany/geany, this repo is just for website junk.

> I'm operating on ignorance here, having never had someone even say the word "Geany like Genie?" and wanted to know what is the point of Geany

Geany is a lightweight, portable editor that provides lots of functionality that you'd expect from full-blown IDE, out-of-the-box, and has quite a few plugins to add more functionality. Probably easier to just try it and evaluate it yourself, it's available in almost every Linux distro's package repositories, and there are Windows and Macos installers on the website.

> Perhaps Geany is a holdover from the Fortran days and is still being used by loyalists or?

The project was started in 2006 or 2007 I believe, and while it supports Fortran editing, otherwise has nothing related.

**Comment by elextr** [comment]
Closed as question answered, and obsolete due to new website contents
