### ISSUE TITLE
License

### ISSUE THREAD

**Issue by elextr** [geany/www.geany.org#6]
The content of this repository is AGPL3+ which is fine, but the actual website has a copyright notice on each page, but no license.  Maybe it should be one of the CC-BY family?

**Comment by eht16** [comment]
Yeah, good point.
What exact license do you suggest?
I think CC-BY-NC-SA or CC-BY-SA fit best.

**Comment by b4n** [comment]
I don't think NC is needed, as it prevents some fairly useful uses like publishing in a selling magazine (which could quote the website or such, etc.).  I don't really care which one it is though, and I welcome any counter arguments, I just mention this because not all "commercial" uses are necessarily harmful.

**Comment by elextr** [comment]
Agree with @b4n, CC-BY-SA is good.

**Comment by eht16** [comment]
Like this? https://github.com/geany/www.geany.org/pull/12

**Comment by elextr** [comment]
Well, I personally would have put the license after the copyright holders

`Contents copyright 2019, the Geany development team, Licensed under CC-BY-SA`

since the license doesn't hold the copyright.

And that brings up the point that it should be `Geany development team and contributors` if the website accepts contributions (like Geany itself after the recent change).

**Comment by eht16** [comment]
Yeah, I used just "the Geany contributors" as we did in Geany itself.
